### PR TITLE
Elastic Search Update

### PR DESCRIPTION
**Pull request by srkirkland**
Updated ES & NEST to the new 7.3 version from v2.  Minor changes were made to queries, aggregations, and stats APIs that I needed to account for.  Locally, I was able to rebuild all indexes and order history, searching and most reports seemed to work fine.

There is one report, which uses the aggregation from `GetOrderTrackingEntitiesByRole()`, which is not working.  That report aggregates based on the `purchaserId` field, which is a fully indexed text field.  ES no longer allows this, and recommends you don't do aggregates on text fields.  We can overwrite that recommendation, change to a non-analyzed text field, or add a new field, but we'll have to investigate the impact of our choice.  https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html

### CODE REVIEW

**Comment by jSylvestre** [comment]
@srkirkland FYI, I think the Shared Services Center is who requested those reports.

**Comment by jSylvestre** [comment]
Vendors too

image

**Comment by jSylvestre** [comment]
building codes

image

**Comment by jSylvestre** [comment]
image

**Comment by srkirkland** [comment]
Elastic search indexing appears perfect, but deserialization of the search results are not correctly populating domain objects, leaving Id null.  Likely because it's a protected set.  I'll look into changing the deserialization strategy and other options.

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html

**Comment by srkirkland** [comment]
@jSylvestre Think I fixed it, using a json serializer based on json.net that ES ships as a supported extension

**Pull request merged**
